name: CI

on:
  push:
    branches:
      - master

jobs:
  sync:
    if: github.event.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Install Dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Sync to Glitch Project
        uses: kanadgupta/glitch-sync@main
        with:
          auth-token: "${{ secrets.AUTHTOKEN }}"
          project-id: "${{ secrets.PROJECTID }}"
